spring:
  application:
    name: spring-otel

management:
  otlp:
    metrics:
      export:
        url: "http://localhost:4318/v1/metrics"
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: "http://localhost:4318/v1/traces"
    logging:
      export:
        otlp:
          endpoint: "http://localhost:4318/v1/logs"
  tracing:
    sampling:
      probability: 1.0